/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** API health check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Welcome */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: components["schemas"]["HealthData"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register author account */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterBody"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: components["schemas"]["AuthLoginData"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register/admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register admin account */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterBody"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: components["schemas"]["AuthLoginData"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginBody"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: components["schemas"]["AuthLoginData"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: components["schemas"]["User"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update current user profile */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AuthorProfileUpdateBody"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: components["schemas"]["User"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/api/v1/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request password reset OTP */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EmailBody"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: unknown;
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/resend-otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resend password reset OTP */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EmailBody"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: unknown;
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset password with OTP */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ResetPasswordBody"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: unknown;
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change password (authenticated) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChangePasswordBody"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: unknown;
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/blogs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List published blogs */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    limit?: number;
                    sort_by?: string;
                    sort_order?: "asc" | "desc";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: {
                                data?: components["schemas"]["Blog"][];
                                pagination?: components["schemas"]["Pagination"];
                            };
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/blogs/slug/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get published blog by slug */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: components["schemas"]["Blog"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/blog-categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List blog categories */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    limit?: number;
                    sort_by?: string;
                    sort_order?: "asc" | "desc";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: {
                                data?: components["schemas"]["BlogCategory"][];
                                pagination?: components["schemas"]["Pagination"];
                            };
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/cv-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active CV templates */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    limit?: number;
                    sort_by?: string;
                    sort_order?: "asc" | "desc";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: {
                                data?: components["schemas"]["CvTemplate"][];
                                pagination?: components["schemas"]["Pagination"];
                            };
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/cv-templates/{templateId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get active CV template by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description CV template ID */
                    templateId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: components["schemas"]["CvTemplate"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/authors/{authorId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get public author profile */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Author user ID */
                    authorId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: components["schemas"]["PublicAuthorProfile"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/team": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all team members profiles */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: components["schemas"]["User"][];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/author/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current author profile */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: components["schemas"]["AuthorProfile"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update author profile */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AuthorProfileUpdateBody"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: components["schemas"]["AuthorProfile"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/api/v1/author/blogs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List AuthorBlog */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    limit?: number;
                    sort_by?: string;
                    sort_order?: "asc" | "desc";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: {
                                data?: components["schemas"]["Blog"][];
                                pagination?: components["schemas"]["Pagination"];
                            };
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        /** Create AuthorBlog */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AuthorBlogCreateBody"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: components["schemas"]["Blog"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/author/blogs/{blog_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get AuthorBlog by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Blog ID */
                    blog_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: components["schemas"]["Blog"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Delete AuthorBlog */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Blog ID */
                    blog_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: unknown;
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /** Update AuthorBlog */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Blog ID */
                    blog_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BlogUpdateBody"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: components["schemas"]["Blog"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/api/v1/admin/blogs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List AdminBlog */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    limit?: number;
                    sort_by?: string;
                    sort_order?: "asc" | "desc";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: {
                                data?: components["schemas"]["Blog"][];
                                pagination?: components["schemas"]["Pagination"];
                            };
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        /** Create AdminBlog */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BlogCreateBody"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: components["schemas"]["Blog"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/blogs/{blog_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get AdminBlog by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Blog ID */
                    blog_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: components["schemas"]["Blog"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Delete AdminBlog */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Blog ID */
                    blog_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: unknown;
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /** Update AdminBlog */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Blog ID */
                    blog_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BlogUpdateBody"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: components["schemas"]["Blog"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/api/v1/admin/blog-categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List AdminBlogCategory */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    limit?: number;
                    sort_by?: string;
                    sort_order?: "asc" | "desc";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: {
                                data?: components["schemas"]["BlogCategory"][];
                                pagination?: components["schemas"]["Pagination"];
                            };
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        /** Create AdminBlogCategory */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BlogCategoryCreateBody"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: components["schemas"]["BlogCategory"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/blog-categories/{category_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get AdminBlogCategory by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Blog category ID */
                    category_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: components["schemas"]["BlogCategory"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Delete AdminBlogCategory */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Blog category ID */
                    category_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: unknown;
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /** Update AdminBlogCategory */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Blog category ID */
                    category_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BlogCategoryUpdateBody"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: components["schemas"]["BlogCategory"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/api/v1/admin/cv-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List AdminCvTemplate */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    limit?: number;
                    sort_by?: string;
                    sort_order?: "asc" | "desc";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: {
                                data?: components["schemas"]["CvTemplate"][];
                                pagination?: components["schemas"]["Pagination"];
                            };
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        /** Create AdminCvTemplate */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CvTemplateCreateBody"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: components["schemas"]["CvTemplate"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/cv-templates/{template_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get AdminCvTemplate by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description CV template ID */
                    template_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: components["schemas"]["CvTemplate"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Delete AdminCvTemplate */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description CV template ID */
                    template_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: unknown;
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /** Update AdminCvTemplate */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description CV template ID */
                    template_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CvTemplateUpdateBody"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: components["schemas"]["CvTemplate"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/api/v1/admin/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List AdminTag */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    limit?: number;
                    sort_by?: string;
                    sort_order?: "asc" | "desc";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: {
                                data?: components["schemas"]["Tag"][];
                                pagination?: components["schemas"]["Pagination"];
                            };
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        /** Create AdminTag */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TagCreateBody"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: components["schemas"]["Tag"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/tags/{tag_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get AdminTag by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Tag ID */
                    tag_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: components["schemas"]["Tag"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Delete AdminTag */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Tag ID */
                    tag_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: unknown;
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /** Update AdminTag */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Tag ID */
                    tag_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TagUpdateBody"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: components["schemas"]["Tag"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/api/v1/admin/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List AdminMedia */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    limit?: number;
                    sort_by?: string;
                    sort_order?: "asc" | "desc";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: {
                                data?: components["schemas"]["Media"][];
                                pagination?: components["schemas"]["Pagination"];
                            };
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        /** Create AdminMedia */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MediaCreateBody"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: components["schemas"]["Media"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/media/{media_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get AdminMedia by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Media ID */
                    media_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: components["schemas"]["Media"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Delete AdminMedia */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Media ID */
                    media_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: unknown;
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /** Update AdminMedia */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Media ID */
                    media_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MediaUpdateBody"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: components["schemas"]["Media"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/api/v1/admin/authors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List AdminAuthor */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    limit?: number;
                    sort_by?: string;
                    sort_order?: "asc" | "desc";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: {
                                data?: components["schemas"]["User"][];
                                pagination?: components["schemas"]["Pagination"];
                            };
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        /** Create AdminAuthor */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AuthorCreateBody"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: components["schemas"]["User"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/authors/{author_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get AdminAuthor by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Author ID */
                    author_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: components["schemas"]["User"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Delete AdminAuthor */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Author ID */
                    author_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: unknown;
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /** Update AdminAuthor */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Author ID */
                    author_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AuthorUpdateBody"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: components["schemas"]["User"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/api/v1/admin/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all site settings */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: components["schemas"]["SiteSetting"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        /** Update site settings */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SiteSettingUpdateBody"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: components["schemas"]["SiteSetting"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @example 68a32fb5cde9d68eac1c181f */
        ObjectId: string;
        Pagination: {
            totalRecords?: number;
            totalPages?: number;
            currentPage?: number;
            pageSize?: number;
            hasNextPage?: boolean;
            hasPrevPage?: boolean;
        };
        HealthData: {
            port?: string;
            container_hostname?: string;
            processId?: number;
            environment?: string;
            version?: string;
        };
        /** @enum {string} */
        UserType: "admin" | "author";
        Position: {
            title?: string;
            order?: number;
        };
        /** @enum {string} */
        BlogStatus: "draft" | "published" | "scheduled";
        /** @enum {string} */
        CvTemplateCategory: "modern" | "professional" | "creative" | "minimal" | "academic" | "executive";
        RegisterBody: {
            firstName: string;
            lastName: string;
            /** Format: email */
            email: string;
            password: string;
            phone?: string;
            profileImage?: string;
            title?: string;
            bio?: string;
            tags?: string[];
            location?: string;
            experience?: string;
            certifications?: string[];
            position?: components["schemas"]["Position"];
        };
        AuthorCreateBody: {
            firstName: string;
            lastName: string;
            /** Format: email */
            email: string;
            password: string;
            phone?: string;
            profileImage?: string;
            title?: string;
            bio?: string;
            tags?: string[];
            location?: string;
            experience?: string;
            certifications?: string[];
            position?: components["schemas"]["Position"];
            /** @default true */
            isActive: boolean;
        };
        AuthorUpdateBody: {
            firstName?: string;
            lastName?: string;
            /** Format: email */
            email?: string;
            password?: string;
            phone?: string;
            profileImage?: string;
            title?: string;
            bio?: string;
            tags?: string[];
            location?: string;
            experience?: string;
            certifications?: string[];
            position?: components["schemas"]["Position"];
            isActive?: boolean;
        };
        LoginBody: {
            /** Format: email */
            email: string;
            password: string;
        };
        EmailBody: {
            /** Format: email */
            email: string;
        };
        ResetPasswordBody: {
            token: string;
            /** Format: email */
            email: string;
            password: string;
        };
        ChangePasswordBody: {
            oldPassword: string;
            newPassword: string;
        };
        AuthLoginData: {
            user?: components["schemas"]["User"];
            accessToken?: string;
        };
        User: {
            _id?: components["schemas"]["ObjectId"];
            __t?: components["schemas"]["UserType"];
            firstName?: string;
            lastName?: string;
            /** Format: email */
            email?: string;
            phone?: string;
            profileImage?: string;
            title?: string;
            bio?: string;
            tags?: string[];
            certifications?: string[];
            position?: components["schemas"]["Position"];
            location?: string;
            experience?: string;
            isActive?: boolean;
            /** Format: date-time */
            lastLoginAt?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        AuthorProfile: components["schemas"]["User"] & {
            articleCount?: number;
        };
        AuthorProfileUpdateBody: {
            firstName?: string;
            lastName?: string;
            phone?: string;
            /** Format: uri */
            profileImage?: string;
            title?: string;
            bio?: string;
            tags?: string[];
            location?: string;
            experience?: string;
            certifications?: string[];
            position?: components["schemas"]["Position"];
        };
        PublicAuthorProfile: {
            _id?: components["schemas"]["ObjectId"];
            firstName?: string;
            lastName?: string;
            profileImage?: string;
            title?: string;
            bio?: string;
            tags?: string[];
            certifications?: string[];
            position?: components["schemas"]["Position"];
            location?: string;
            experience?: string;
            articleCount?: number;
        };
        BlogCategory: {
            _id?: components["schemas"]["ObjectId"];
            name?: string;
            slug?: string;
            description?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        BlogCategoryCreateBody: {
            name: string;
            slug?: string;
            description?: string;
        };
        BlogCategoryUpdateBody: {
            name?: string;
            slug?: string;
            description?: string;
        };
        Blog: {
            _id?: components["schemas"]["ObjectId"];
            title?: string;
            content?: string;
            slug?: string;
            excerpt?: string;
            author?: string;
            authorId?: components["schemas"]["ObjectId"];
            status?: components["schemas"]["BlogStatus"];
            /** @enum {string} */
            visibility?: "public" | "private";
            tags?: string[];
            viewCount?: number;
            /** Format: date-time */
            publishedAt?: string;
            /** Format: date-time */
            scheduledAt?: string;
            categories?: components["schemas"]["BlogCategory"][];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        BlogCreateBody: {
            title: string;
            content: string;
            slug?: string;
            author: string;
            status?: components["schemas"]["BlogStatus"];
            /**
             * @default public
             * @enum {string}
             */
            visibility: "public" | "private";
            tags?: string[];
            categories?: components["schemas"]["ObjectId"][];
            /** Format: date-time */
            scheduledAt?: string;
        };
        AuthorBlogCreateBody: {
            title: string;
            content: string;
            slug?: string;
            excerpt?: string;
            /** Format: uri */
            featuredImage?: string;
            status?: components["schemas"]["BlogStatus"];
            /**
             * @default public
             * @enum {string}
             */
            visibility: "public" | "private";
            tags?: string[];
            categories?: components["schemas"]["ObjectId"][];
            /** Format: date-time */
            scheduledAt?: string;
        };
        BlogUpdateBody: {
            title?: string;
            content?: string;
            slug?: string;
            author?: string;
            status?: components["schemas"]["BlogStatus"];
            /** @enum {string} */
            visibility?: "public" | "private";
            tags?: string[];
            categories?: components["schemas"]["ObjectId"][];
            /** Format: date-time */
            scheduledAt?: string;
        };
        CvTemplate: {
            _id?: components["schemas"]["ObjectId"];
            name?: string;
            slug?: string;
            category?: components["schemas"]["CvTemplateCategory"];
            /** Format: uri */
            image_url?: string;
            /** Format: uri */
            preview_url?: string;
            /** Format: uri */
            thumbnail_url?: string;
            description?: string;
            is_active?: boolean;
            is_premium?: boolean;
            sort_order?: number;
            tags?: string[];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CvTemplateCreateBody: {
            name: string;
            slug?: string;
            category: components["schemas"]["CvTemplateCategory"];
            /** Format: uri */
            image_url: string;
            /** Format: uri */
            preview_url?: string;
            /** Format: uri */
            thumbnail_url?: string;
            description?: string;
            is_active?: boolean;
            is_premium?: boolean;
            sort_order?: number;
            tags?: string[];
        };
        CvTemplateUpdateBody: {
            name?: string;
            slug?: string;
            category?: components["schemas"]["CvTemplateCategory"];
            /** Format: uri */
            image_url?: string;
            /** Format: uri */
            preview_url?: string;
            /** Format: uri */
            thumbnail_url?: string;
            description?: string;
            is_active?: boolean;
            is_premium?: boolean;
            sort_order?: number;
            tags?: string[];
        };
        Tag: {
            _id?: components["schemas"]["ObjectId"];
            /** @example resume */
            name?: string;
            /** @example #F47A3A */
            color?: string;
            /** @example 24 */
            usageCount?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        TagCreateBody: {
            /** @example remote-work */
            name: string;
            /** @example #F47A3A */
            color?: string;
        };
        TagUpdateBody: {
            /** @example remote-work */
            name?: string;
            /** @example #F47A3A */
            color?: string;
        };
        Media: {
            _id?: components["schemas"]["ObjectId"];
            /**
             * Format: uri
             * @example https://storage.example.com/uploads/image.png
             */
            imageUrl?: string;
            /** @example hero-banner.png */
            filename?: string;
            /** @example 204800 */
            size?: number;
            /** @example image/png */
            mimeType?: string;
            /** @example Hero banner illustration */
            altText?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        MediaCreateBody: {
            /**
             * Format: uri
             * @example https://storage.example.com/uploads/image.png
             */
            imageUrl: string;
            /** @example hero-banner.png */
            filename: string;
            /** @example 204800 */
            size?: number;
            /** @example image/png */
            mimeType?: string;
            /** @example Hero banner illustration */
            altText?: string;
        };
        MediaUpdateBody: {
            /** Format: uri */
            imageUrl?: string;
            filename?: string;
            size?: number;
            mimeType?: string;
            altText?: string;
        };
        SocialLinks: {
            /** @example https://x.com/cvjury */
            x?: string;
            /** @example https://linkedin.com/company/cvjury */
            linkedin?: string;
            /** @example https://facebook.com/cvjury */
            facebook?: string;
            /** @example https://instagram.com/cvjury */
            instagram?: string;
        };
        SiteSetting: {
            _id?: components["schemas"]["ObjectId"];
            /** @example CVjury */
            siteName?: string;
            /** @example https://cvjury.com/logo.svg */
            siteLogo?: string;
            /** @example https://cvjury.com/favicon.ico */
            favicon?: string;
            /**
             * Format: email
             * @example hello@cvjury.com
             */
            contactEmail?: string;
            /** @example +44 20 1234 5678 */
            phone?: string;
            /** @example 123 High Street, London, UK */
            address?: string;
            /** @example Europe/London */
            timezone?: string;
            socialLinks?: components["schemas"]["SocialLinks"];
            /** @example CVJury — Professional CV Builder & Career Resources */
            metaTitle?: string;
            /** @example Build a professional CV in minutes... */
            metaDescription?: string;
            /**
             * @example User-agent: *
             *     Allow: /
             *     Sitemap: https://cvjury.com/sitemap.xml
             */
            robotsTxt?: string;
            /** @example CVJury — Professional CV Builder */
            ogTitle?: string;
            /** @example Build a professional CV in minutes... */
            ogDescription?: string;
            /** @example https://cvjury.com/og-image.png */
            ogImage?: string;
            /** @example summary_large_image */
            twitterCardType?: string;
            /** @example @cvjury */
            twitterHandle?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        SiteSettingUpdateBody: {
            siteName?: string;
            /** Format: uri */
            siteLogo?: string;
            /** Format: uri */
            favicon?: string;
            /** Format: email */
            contactEmail?: string;
            phone?: string;
            address?: string;
            timezone?: string;
            socialLinks?: components["schemas"]["SocialLinks"];
            metaTitle?: string;
            metaDescription?: string;
            robotsTxt?: string;
            ogTitle?: string;
            ogDescription?: string;
            /** Format: uri */
            ogImage?: string;
            /** @enum {string} */
            twitterCardType?: "summary" | "summary_large_image" | "app" | "player";
            twitterHandle?: string;
        };
    };
    responses: {
        /** @description Validation or bad request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    message?: string;
                    error?: string[];
                };
            };
        };
        /** @description Missing or invalid token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    message?: string;
                };
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    message?: string;
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
